spring:
  application:
    name: professor_oline
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-escola
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    # Configuração do Feign Client
    feign:
      client:
        config:
          ms-professor:
            connectTimeout: 5000
            readTimeout: 5000
    ms-professor:
      ribbon:
        # URL completa do microsserviço Professor (o serviço está na porta 8081)
        listOfServers: http://localhost:8081