services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: db-escola  # NOME ÚNICO
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=ms-escola'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=123456'
    ports:
      - '5432:5432' # Porta padrão
    networks:
      - escola-network

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: pgadmin-escola
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@admin.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    ports:
      - '15432:80' # Porta do PgAdmin Escola
    networks:
      - escola-network
    depends_on:
      - postgres

networks:
  escola-network:
    driver: bridge